import 'package:flutter/cupertino.dart';
import 'package:get/get.dart';

class MyLanguage extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'zh_CN': {
          'home_title': '下载列表',
          'downloadDialog_Title': '检索文件',
          'downloadDialog_Hint': '输入文件hash',
          'downloadDialog_Button': '检索',
          'downloadDialog_failure': '未查询到文件',
          'settingPage_title': "设置",
          'settingPage_requestURI': "请求地址",
          'settingPage_language': "语言",
          'settingPage_darkMode': "夜间主题",
          'settingPage_URIDialog_content': "默认：https://ipfs.io",
          'settingPage_URIDialog_OK': "确认",
          'settingPage_LanguageDialog_Title': "设置语言",
          'settingPage_LanguageDialog_Chinese': "简体中文",
          'settingPage_LanguageDialog_English': "英语（美国）",
          'downloadInfoPage_title': "下载项信息",
          'downloadInfoPage_date': "日期",
          'downloadInfoPage_fileSize': "文件大小",
          'downloadInfoPage_fileName': "文件名称",
          'downloadInfoPage_fileType': "文件类型",
          'downloadInfoPage_fileType_hint': "选择类型",
          'downloadInfoPage_fileType_text/html': "文本、网页",
          'downloadInfoPage_fileType_media': "媒体文件",
          'downloadInfoPage_fileType_picture': "图片",
          'downloadInfoPage_Button': "下载",
          'downloadInfoPage_ContentNull': "该项内容不能为空",
          'changeFileInfoPage_Title': "修改文件信息",
          'changeFileInfoPage_Button': "修改",
          'changeFileInfoPage_date': "日期",
          'changeFileInfoPage_fileSize': "文件大小",
          'changeFileInfoPage_fileName': "文件名称",
          'changeFileInfoPage_fileType': "文件类型",
          'changeFileInfoPage_ContentNull': '该项内容不能为空',
          'changeFileInfoPage_fileType_hint': "选择类型",
          'changeFileInfoPage_fileType_text/html': "文本、网页",
          'changeFileInfoPage_fileType_media': "媒体文件",
          'changeFileInfoPage_fileType_picture': "图片",
          'listItem_date': '日期',
          'listItem_fileSize': '文件大小',
          'listItem_dialog_changeFileInfo': '修改文件信息',
          'listItem_dialog_deleteFile': '删除文件',
          'search_page_hint': '文件名称',
        },
        'en_US': {
          'home_title': 'Download List',
          'downloadDialog_Title': 'Search File',
          'downloadDialog_Hint': 'please input the hash',
          'downloadDialog_Button': 'search',
          'downloadDialog_failure': 'ops! searching is failed',
          'settingPage_title': "Settings",
          'settingPage_requestURI': "Request Address",
          'settingPage_language': "Language",
          'settingPage_darkMode': "DarkMode",
          'settingPage_URIDialog_content': "default: https://ipfs.io",
          'settingPage_URIDialog_OK': "OK",
          'settingPage_LanguageDialog_Title': "Language Setting",
          'settingPage_LanguageDialog_Chinese': "Simplified-Chinese",
          'settingPage_LanguageDialog_English': "English-USA",
          'downloadInfoPage_title': "DownLoad Item Info",
          'downloadInfoPage_date': "Date",
          'downloadInfoPage_fileSize': "File Size",
          'downloadInfoPage_fileName': "File Name",
          'downloadInfoPage_fileType': "File Type",
          'downloadInfoPage_fileType_hint': "Select One",
          'downloadInfoPage_fileType_text/html': "text/html",
          'downloadInfoPage_fileType_meida': "meida",
          'downloadInfoPage_fileType_picture': "picture",
          'downloadInfoPage_Button': "Download",
          'downloadInfoPage_ContentNull': "Should not be empty",
          'changeFileInfoPage_Title': "Change File Information",
          'changeFileInfoPage_Button': "change",
          'changeFileInfoPage_date': "Date",
          'changeFileInfoPage_fileSize': "File Size",
          'changeFileInfoPage_fileName': "File Name",
          'changeFileInfoPage_fileType': "File Type",
          'changeFileInfoPage_ContentNull': 'Should not be empty',
          'changeFileInfoPage_fileType_hint': "Select One",
          'changeFileInfoPage_fileType_text/html': "text/html",
          'changeFileInfoPage_fileType_media': "media",
          'changeFileInfoPage_fileType_picture': "picture",
          'listItem_date': 'Date',
          'listItem_fileSize': 'File Size',
          'listItem_dialog_changeFileInfo': 'Change file info',
          'listItem_dialog_deleteFile': 'Delete file',
          'search_page_hint': 'file name',
        }
      };
}
